In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

In [2]:
from sklearn.datasets import load_boston

In [13]:
boston = load_boston()

In [14]:
bdata = boston.data
bdata

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [10]:
data.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [16]:
df = pd.DataFrame(bdata,columns = boston.feature_names)

In [17]:
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [18]:
x = boston.data
y = boston.target

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25,random_state = 80)

In [23]:
from sklearn.preprocessing import MinMaxScaler

In [24]:
data_set = MinMaxScaler(feature_range=(0,1))

In [25]:
x_train = data_set.fit_transform(x_train)
x_test  = data_set.fit_transform(x_test)


# Reshaping of the y -train dataset

In [26]:
y_train = y_train.reshape(-1,1)

In [28]:
y_train  = data_set.fit_transform(y_train)

array([[1.77739352e-01, 0.00000000e+00, 6.46627566e-01, ...,
        8.08510638e-01, 1.00000000e+00, 3.59547461e-01],
       [3.31896325e-02, 0.00000000e+00, 7.00879765e-01, ...,
        2.23404255e-01, 2.22678905e-01, 3.97626932e-01],
       [6.44654306e-04, 0.00000000e+00, 4.93401760e-01, ...,
        3.61702128e-01, 9.89787685e-01, 1.56181015e-01],
       ...,
       [1.63773202e-01, 0.00000000e+00, 6.46627566e-01, ...,
        8.08510638e-01, 7.34353724e-01, 3.41335541e-01],
       [1.62482806e-03, 4.73684211e-01, 1.09237537e-01, ...,
        2.76595745e-01, 9.64546876e-01, 7.80905077e-02],
       [8.20370206e-04, 0.00000000e+00, 1.31598240e-01, ...,
        4.25531915e-01, 9.85021938e-01, 9.93377483e-02]])

# Develop Regression model for prediction

In [31]:
from sklearn.linear_model import LinearRegression

In [32]:
lr = LinearRegression()

In [33]:
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [34]:
predicts = lr.predict(x_test)

In [35]:
predicts

array([[ 0.2394436 ],
       [ 0.70470649],
       [ 0.36512546],
       [ 0.31749449],
       [ 0.36753545],
       [ 0.5807883 ],
       [ 0.81200934],
       [ 0.32618238],
       [ 0.41846503],
       [ 0.21995664],
       [ 0.15474255],
       [ 0.27909837],
       [ 0.34301247],
       [ 0.30894113],
       [ 0.26969096],
       [ 0.40885054],
       [ 0.48816105],
       [ 0.22442743],
       [ 0.34019459],
       [ 0.40195611],
       [-0.0009787 ],
       [ 0.28849508],
       [ 0.2986122 ],
       [ 0.2095336 ],
       [ 0.19032204],
       [ 0.6054565 ],
       [ 0.33097348],
       [ 0.14042423],
       [ 0.32049985],
       [ 0.36894008],
       [ 0.20697948],
       [ 0.44121065],
       [ 0.40812765],
       [ 0.28305834],
       [ 0.12561794],
       [ 0.16323498],
       [ 0.63819351],
       [ 0.27991249],
       [ 0.21263603],
       [ 0.07860545],
       [ 0.50372466],
       [ 0.63767115],
       [ 0.42807874],
       [ 0.44908908],
       [ 0.3455756 ],
       [ 0

# RANDOM FOREST

In [36]:
from sklearn.ensemble import RandomForestRegressor

In [37]:
rf = RandomForestRegressor(random_state = 33)

In [38]:
rf.fit(x_train,y_train)

C:\Users\BRAKAY\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\BRAKAY\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=33, verbose=0,
                      warm_start=False)

In [39]:
predi = rf.predict(x_test)

In [40]:
predi

array([0.32022222, 0.86177778, 0.34511111, 0.31977778, 0.322     ,
       0.66422222, 0.91111111, 0.35777778, 0.31422222, 0.36666667,
       0.206     , 0.31933333, 0.30666667, 0.29377778, 0.31488889,
       0.40022222, 0.56155556, 0.24755556, 0.31422222, 0.32866667,
       0.31577778, 0.26155556, 0.26266667, 0.29933333, 0.20444444,
       0.54044444, 0.29933333, 0.278     , 0.33888889, 0.32844444,
       0.27577778, 0.37577778, 0.39488889, 0.28577778, 0.31      ,
       0.28888889, 0.60088889, 0.30911111, 0.31777778, 0.17311111,
       0.63622222, 0.86155556, 0.39577778, 0.62222222, 0.38266667,
       0.44066667, 0.29555556, 0.45555556, 0.35733333, 0.24688889,
       0.19755556, 0.29822222, 0.22111111, 0.35711111, 0.25911111,
       0.19355556, 0.60977778, 0.302     , 0.336     , 0.26977778,
       0.33022222, 0.38422222, 0.36866667, 0.39044444, 0.53911111,
       0.55755556, 0.30311111, 0.55866667, 0.18222222, 0.18844444,
       0.33355556, 0.25288889, 0.18911111, 0.32311111, 0.40933

In [41]:
predi = predi.reshape(-1,1)

In [42]:
predi

array([[0.32022222],
       [0.86177778],
       [0.34511111],
       [0.31977778],
       [0.322     ],
       [0.66422222],
       [0.91111111],
       [0.35777778],
       [0.31422222],
       [0.36666667],
       [0.206     ],
       [0.31933333],
       [0.30666667],
       [0.29377778],
       [0.31488889],
       [0.40022222],
       [0.56155556],
       [0.24755556],
       [0.31422222],
       [0.32866667],
       [0.31577778],
       [0.26155556],
       [0.26266667],
       [0.29933333],
       [0.20444444],
       [0.54044444],
       [0.29933333],
       [0.278     ],
       [0.33888889],
       [0.32844444],
       [0.27577778],
       [0.37577778],
       [0.39488889],
       [0.28577778],
       [0.31      ],
       [0.28888889],
       [0.60088889],
       [0.30911111],
       [0.31777778],
       [0.17311111],
       [0.63622222],
       [0.86155556],
       [0.39577778],
       [0.62222222],
       [0.38266667],
       [0.44066667],
       [0.29555556],
       [0.455